import { useEffect, useState, type FormEvent } from 'react'
import type { PhrasePack } from '../types'
import { copyTextToClipboard } from '../utils/clipboard'
import { AI_FORMAT_PROMPT, importPack, importPastedJson, PHRASE_PACK_EXAMPLE } from '../utils/import'

export function ImportPanel({ onImport }: { onImport: (pack: PhrasePack) => void }) {
  const [name, setName] = useState('')
  const [pastedJson, setPastedJson] = useState('')
  const [file, setFile] = useState<File | null>(null)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)
  const [showFormat, setShowFormat] = useState(false)

  useEffect(() => {
    if (!copied) return
    const timeout = window.setTimeout(() => setCopied(false), 2200)
    return () => window.clearTimeout(timeout)
  }, [copied])

  function clearFileInput() {
    setFile(null)
    const input = document.getElementById('pack-file') as HTMLInputElement | null
    if (input) input.value = ''
  }

  function submitPastedJson(event: FormEvent) {
    event.preventDefault()
    setError('')
    try {
      const pack = importPastedJson(pastedJson, name)
      onImport(pack)
      setPastedJson('')
      setName('')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not import this JSON.')
    }
  }

  async function submitFile(event: FormEvent) {
    event.preventDefault()
    setError('')
    if (!file) {
      setError('Choose a JSON or CSV file.')
      return
    }

    try {
      const pack = await importPack(file, name)
      onImport(pack)
      setName('')
      clearFileInput()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not import this file.')
    }
  }

  async function copyAiPrompt() {
    const copyResult = copyTextToClipboard(AI_FORMAT_PROMPT)
    setError('')
    setCopied(false)
    const didCopy = await copyResult
    if (didCopy) {
      setCopied(true)
    } else {
      setError('Automatic copy is not available in this browser.')
    }
  }

  return (
    <section className="import-panel" aria-labelledby="import-title">
      <div className="import-intro">
        <p className="eyebrow">Bring your own material</p>
        <h2 id="import-title">Import a phrase pack</h2>
        <p className="muted">Paste PhraseRecall JSON generated by an AI, or import an existing JSON or CSV file.</p>

        <div className="ai-tools">
          <p>Creating a pack with AI?</p>
          <div className="button-row">
            <button className="secondary" type="button" onClick={copyAiPrompt}>Copy AI prompt</button>
            <button
              className="text-button format-button"
              type="button"
              aria-expanded={showFormat}
              onClick={() => setShowFormat((current) => !current)}
            >
              {showFormat ? 'Hide format' : 'View format'}
            </button>
          </div>
          {copied && <p className="copy-confirmation" role="status">AI prompt copied</p>}
          {showFormat && (
            <div className="format-example">
              <p className="eyebrow">PhraseRecall JSON format</p>
              <pre><code>{PHRASE_PACK_EXAMPLE}</code></pre>
            </div>
          )}
        </div>
      </div>

      <div className="import-content">
        <form onSubmit={submitPastedJson} className="import-form">
          <label>
            PhraseRecall JSON
            <textarea
              value={pastedJson}
              onChange={(event) => setPastedJson(event.target.value)}
              placeholder={PHRASE_PACK_EXAMPLE}
              rows={14}
              spellCheck={false}
            />
          </label>
          <label>
            Pack name <span className="label-note">only needed for legacy JSON arrays or CSV</span>
            <input value={name} onChange={(event) => setName(event.target.value)} placeholder="Travel French" />
          </label>
          {error && <p className="error" role="alert">{error}</p>}
          <button className="primary" type="submit">Import pasted JSON</button>
        </form>

        <details className="file-import">
          <summary>Import a JSON or CSV file instead</summary>
          <form onSubmit={submitFile} className="import-form">
            <label>
              Phrase file
              <input id="pack-file" type="file" accept=".json,.csv,application/json,text/csv" onChange={(event) => setFile(event.target.files?.[0] ?? null)} />
            </label>
            <p className="muted">The pack name above is required for CSV and legacy JSON arrays. New-format JSON includes its own name.</p>
            <button className="secondary" type="submit">Import file</button>
          </form>
        </details>
      </div>
    </section>
  )
}
